"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export const translations = {
  en: {
    // --- Shared / Nav ---
    live: "LIVE",
    profile: "Profile",
    settings: "Settings",
    logout: "Logout",
    erpSubtitle: "EMM Hardware ERP · V2.4",

    // --- Sidebar ---
    dashboard: "Dashboard",
    hr: "HR",
    marketing: "Marketing",
    onlineSales: "Online Sales",
    employees: "Employees",
    attendance: "Attendance",
    payroll: "Payroll",
    performance: "Performance",
    reports: "Reports",
    productCatalog: "Product Catalog",
    onlineOrders: "Online Orders",
    stockProduction: "Stock & Production",
    deliveryTracking: "Delivery Tracking",
    returnsRefunds: "Returns & Refunds",
    campaigns: "Campaigns",
    analytics: "Analytics",
    segmentation: "Segmentation",
    budget: "Budget",
    promotions: "Promotions",


    // --- Sales Dashboard ---
    onlineSalesDashboard: "Online Sales Dashboard",
    totalRevenue2: "Total Revenue",
    pendingShipments: "Pending Shipments",
    returns: "Returns",
    avgOrderValue: "Avg Order Value",
    perTransaction: "per transaction",
    newCustomers: "New Customers",
    customerLtv: "Customer LTV",
    avgLifetime: "average lifetime",
    revenueOverview: "Revenue Overview",
    monthlyPerf: "Monthly performance",
    revenueUSD: "Revenue (USD)",
    topProducts: "Top Products",
    unitsSoldMonth: "Units sold this month",
    searchOrdersPlaceholder: "Search orders...",
    noOrdersMatchFilter: "No orders match your filter",
    salesByChannel: "Sales by Channel",
    revenueSplitMonth: "Revenue split this month",
    directSales: "Direct Sales",
    wholesale: "Wholesale",
    distributor: "Distributor",
    onlineStore: "Online Store",
    monthlyGoal: "Monthly Goal",
    daysLeft: "8 days left",
    invoice: "Invoice",
    report: "Report",
    shipment: "Shipment",
    todayChange: "-3 today",

    // --- Catalog Page ---
    productCatalogTitle: "Product Catalog",
    addProduct: "Add Product",
    totalProducts: "Total Products",
    inStock: "In Stock",
    lowStock: "Low Stock",
    catalogValue: "Catalog Value",
    categories: "Categories",
    outOfStock: "Out of Stock",
    avgPrice: "Avg Price",
    totalSkus: "Total SKUs",
    searchProducts: "Search products...",
    noProductsMatch: "No products match your filter",
    productTypes: "product types",
    needsRestocking: "needs restocking",
    perUnit: "per unit",
    activeListings: "active listings",
    inStockLabel: "In Stock",
    lowStockLabel: "Low Stock",
    outOfStockLabel: "Out of Stock",
    needsReorder: "needs reorder",
    thisMonth2: "+3 this month",
    tndEquivalent: "TND equivalent",

    // --- Orders Page ---
    onlineOrders: "Online Orders",
    newOrder2: "New Order",
    totalOrdersKpi2: "Total Orders",
    completedKpi2: "Completed",
    processingKpi: "Processing",
    pendingKpi2: "Pending",
    allOrdersTitle: "All Orders",
    searchOrders2: "Search orders...",
    noOrdersMatch2: "No orders match your filter",
    avgOrder: "Avg Order",
    completionRate: "Completion Rate",
    fulfilled: "fulfilled",
    inTransitSub: "in transit",
    awaitingSub: "awaiting",
    allOrders: "All Orders",
    order: "Order",
    orders: "orders",
    perOrder: "per order",
    thisPeriod: "this period",
    fulfillment: "fulfillment",
    price: "Price",
    stock: "Stock",
    category: "Category",
    amount: "Amount",
    customer: "Customer",

    // --- Returns Page ---
    returnsRefunds: "Returns & Refunds",
    newReturn: "New Return",
    totalReturns: "Total Returns",
    pendingReview: "Pending Review",
    refunded: "Refunded",
    totalValue: "Total Value",
    refundRate: "Refund Rate",
    refundedValue: "Refunded Value",
    avgReturn: "Avg Return",
    rejectedKpi2: "Rejected",
    returnRequests: "Return Requests",
    searchReturns: "Search returns...",
    noReturnsMatch: "No returns match your filter",
    reason: "Reason",
    ofTotalOrders: "of total orders",
    paidOut: "paid out",
    perReturn: "per return",
    notApproved: "not approved",
    actionNeeded: "action needed",
    processed: "processed",
    inReturns: "in returns",
    requests: "requests",

    // --- Stock Page ---
    stockProduction2: "Stock & Production",
    restockOrder: "Restock Order",
    totalSkusKpi: "Total SKUs",
    inStockKpi: "In Stock",
    alertsKpi: "Alerts",
    outOfStockKpi: "Out of Stock",
    totalUnits: "Total Units",
    reorderNeeded: "Reorder Needed",
    lastSync: "Last Sync",
    stockLevels: "Stock Levels",
    searchStock: "Search stock...",
    noStockMatch: "No items match your filter",
    stockVsMinimum: "Stock vs Minimum",
    stockAlerts: "Stock Alerts",
    itemsNeedingAttention: "Items needing attention",
    currentLevelsVsThreshold: "Current levels vs reorder threshold",
    acrossAllSkus: "across all SKUs",
    skusBelowMinimum: "SKUs below minimum",
    realTimeData: "real-time data",
    tracked: "tracked",
    healthy: "healthy",
    needsAction: "needs action",
    reorderNow: "reorder now",
    minimum: "Minimum",
    reorderQty: "Reorder Qty",
    current: "Current",

    // --- Tracking Page ---
    deliveryTracking2: "Delivery Tracking",
    newShipment: "New Shipment",
    totalShipments: "Total Shipments",
    delivered: "Delivered",
    inTransit: "In Transit",
    failedKpi: "Failed",
    pendingShip: "Pending",
    deliveryRate: "Delivery Rate",
    carriersKpi: "Carriers",
    avgEta: "Avg ETA",
    shipmentTracker: "Shipment Tracker",
    searchShipments: "Search shipments...",
    noShipmentsMatch: "No shipments match your filter",
    shipmentsByCarrier: "Shipments by Carrier",
    volumeSplitMonth: "Volume split this month",
    activityFeed: "Activity Feed",
    liveUpdates: "Live updates",
    quickActions: "Quick Actions",
    shortcuts: "Shortcuts",
    deliveryGoal: "Delivery Goal",
    trackingNo: "Tracking No.",
    carrier: "Carrier",
    shipped: "Shipped",
    eta: "ETA",
    thisMonthSub: "this month",
    completedSub: "completed",
    onTheWay: "on the way",
    needsActionSub: "needs action",
    awaitingDispatch: "awaiting dispatch",
    successRate: "success rate",
    daysToDeliver: "days to deliver",
    stillMoving: "still moving",
    shipments: "shipments",

    // --- Login ---
    authLabel: "Authentication",
    signInTitle: "Sign in to your account",
    emailLabel: "Email",
    emailPlaceholder: "you@company.com",
    passwordLabel: "Password",
    signInButton: "Sign In →",
    invalidCredentials: "Invalid email or password",
    copyright: "© 2026 EMM Hardware ERP",
    erpTagline: "Secure enterprise management platform for HR, Marketing, Sales and Operations.",
    statRevenue: "Total Revenue",
    statOrders: "Active Orders",
    statUptime: "Uptime",

    // --- Profile ---
    accountLabel: "Account",
    myProfile: "My Profile",
    profileInformation: "Profile Information",
    fullName: "Full Name",
    emailField: "Email",
    roleField: "Role",
    saveChanges: "Save Changes",

    // --- Settings ---
    systemLabel: "System",
    settingsTitle: "Settings",
    securitySection: "Security",
    changePassword: "Change Password",
    enableTwoFactor: "Enable Two-Factor Authentication",
    preferencesSection: "Preferences",
    enableNotifications: "Enable Notifications",
    toggleDarkMode: "Toggle Dark Mode",
    dangerZone: "Danger Zone",
    deleteAccount: "Delete Account",

    // --- Common table/page actions ---
    export: "Export",
    exportCsv: "Export CSV",
    exportPdf: "Export PDF",
    exportExcel: "Export Excel",
    exportAll: "Export All",
    search: "Search",
    searchEmployee: "Search employee...",
    searchUser: "Search user...",
    searchOrders: "Search orders...",
    allStatus: "All Status",
    allTypes: "All Types",
    allRatings: "All Ratings",
    noResults: "No results match your filter",
    ofText: "of",
    records: "records",

    // --- Status labels ---
    active: "Active",
    inactive: "Inactive",
    onLeave: "On Leave",
    approved: "Approved",
    pending: "Pending",
    rejected: "Rejected",
    completed: "Completed",
    processing: "Processing",
    cancelled: "Cancelled",
    paid: "Paid",
    hold: "Hold",
    excellent: "Excellent",
    good: "Good",
    average: "Average",
    poor: "Poor",
    paused: "Paused",
    planned: "Planned",
    scheduled: "Scheduled",
    growing: "Growing",
    stable: "Stable",
    declining: "Declining",
    atRisk: "At Risk",

    // --- Admin Dashboard ---
    adminDashboard: "Admin Dashboard",
    adminSubtitle: "Feb 2026 · EMM ERP · v2.4",
    newReport: "+ New Report",
    totalEmployees: "Total Employees",
    monthlyRevenue: "Monthly Revenue (TND)",
    totalOrders: "Total Orders",
    activeCampaigns: "Active Campaigns",
    allDepartments: "all departments",
    currentlyWorking: "currently working",
    allTime: "all time",
    activeCampaignsCount: "active this month",
    newUsers: "New Users",
    serverLoad: "Server Load",
    pendingApprovals: "Pending Approvals",
    securityScore: "Security Score",
    optimalPerformance: "optimal performance",
    requiresAction: "requires action",
    lastAuditPassed: "last audit passed",
    businessOverview: "Business Overview",
    monthlyPerformance: "Monthly performance",
    revenueTND: "Revenue (TND)",
    ordersPerMonth: "Orders / Month",
    recentUsers: "Recent Users",
    topModules: "Top Modules",
    usageThisMonth: "Usage this month",
    systemHealth: "System Health",
    databaseUsage: "Database Usage",
    apiStability: "API Stability",
    totalRevenue: "Total Revenue",

    // --- HR Dashboard ---
    hrDashboard: "HR Dashboard",
    pendingPayroll: "Pending Payroll (TND)",
    workingHours: "Working Hours",
    attrition: "Attrition",
    totalEmployeesKpi: "Total Employees",
    activeWorkforce: "active workforce",
    performanceScore: "Performance Score",
    newHires: "New Hires",
    avgTenure: "Avg Tenure",
    avgPerEmployee: "average per employee",
    payrollOverview: "Payroll Overview",
    totalPayroll: "Total Payroll",
    avgPerformance: "Avg Performance",
    payrollTND: "Payroll (TND)",
    performanceScoreChart: "Performance Score",
    topPerformers: "Top Performers",
    performanceScoreThisMonth: "Performance score this month",
    addEmployee: "+ Add Employee",

    // --- HR Employees ---
    employeeManagement: "Employee Management",
    humanResources: "Human Resources · EMM ERP · v2.4",
    totalEmployeesKpiShort: "Total Employees",
    onLeaveKpi: "On Leave",
    cdiContracts: "CDI Contracts",
    permanentStaff: "permanent staff",
    allEmployees: "All Employees",
    employee: "Employee",
    position: "Position",
    dept: "Dept",
    contract: "Contract",
    status: "Status",
    joined: "Joined",
    noEmployeesMatch: "No employees match your filter",

    // --- HR Attendance ---
    attendanceAbsences: "Attendance & Absences",
    totalRequests: "Total Requests",
    thisMonth: "this month",
    approvedKpi: "Approved",
    processed: "processed",
    pendingKpi: "Pending",
    awaitingAction: "awaiting action",
    rejectedKpi: "Rejected",
    notApproved: "not approved",
    attendanceRecords: "Attendance Records",
    approveRequests: "Approve Requests",
    date: "Date",
    type: "Type",
    hours: "Hours",
    noAttendanceMatch: "No records match your filter",
    annualLeave: "Annual Leave",
    sickLeave: "Sick Leave",
    remoteWork: "Remote Work",
    unpaidLeave: "Unpaid Leave",
    unauthorized: "Unauthorized",

    // --- HR Payroll ---
    payrollManagement: "Payroll Management",
    totalNetPayroll: "Total Net Payroll",
    totalBonuses: "Total Bonuses",
    distributed: "distributed",
    slipsPaid: "Slips Paid",
    pendingHold: "Pending / Hold",
    payrollRecords: "Payroll Records",
    generatePayslips: "Generate Payslips",
    baseTND: "Base (TND)",
    bonus: "Bonus",
    deductions: "Deductions",
    netTND: "Net (TND)",
    month: "Month",
    noPayrollMatch: "No records match your filter",

    // --- HR Performance ---
    performanceTracking: "Performance Tracking",
    avgScore: "Avg Score",
    teamAverage: "team average",
    excellentCount: "Excellent",
    topPerformersKpi: "top performers",
    evaluations: "Evaluations",
    thisCycle: "this cycle",
    needsReview: "Needs Review",
    belowTarget: "below target",
    evaluationsTable: "Evaluations",
    score: "Score",
    manager: "Manager",
    rating: "Rating",
    addEvaluation: "+ Add Evaluation",
    topPerformersThisCycle: "Performance score this cycle",
    noPerformanceMatch: "No records match your filter",

    // --- HR Reports ---
    hrReports: "HR Reports",
    totalReports: "Total Reports",
    available: "available",
    generatedToday: "Generated Today",
    thisSession: "this session",
    monthlyExports: "Monthly Exports",
    pendingReports: "Pending Reports",
    notYetGenerated: "not yet generated",
    recentExports: "Recent Exports",
    latestFiles: "Latest downloaded files",
    redownload: "Re-download",
    payrollReport: "Payroll Report",
    payrollReportDesc: "Monthly salary breakdown with bonuses and deductions",
    absenceReport: "Absence & Leave Report",
    absenceReportDesc: "Employee leave records, sick days, and absences",
    employeeList: "Employee List",
    employeeListDesc: "Full directory of all staff with contracts and status",
    performanceReport: "Performance Report",
    performanceReportDesc: "Team performance scores, ratings and evaluations",
    monthly: "Monthly",
    onDemand: "On Demand",
    quarterly: "Quarterly",
    lastGenerated: "Last generated",

    // --- Sales / Admin pages ---
    hrEmployees: "HR Employees",
    marketingEmployees: "Marketing Employees",
    marketingDept: "Marketing Department · EMM ERP · v2.4",
    hrDept: "Human Resources · EMM ERP · v2.4",
    totalHRStaff: "Total HR Staff",
    totalMarketing: "Total Marketing",
    inDepartment: "in department",
    salesOrders: "Sales Orders",
    onlineSalesSubtitle: "Online Sales · EMM ERP · v2.4",
    newOrder: "+ New Order",
    totalOrdersKpi: "Total Orders",
    completedKpi: "Completed",
    successfullyDone: "successfully done",
    pendingCount: "Pending",
    revenueThisPeriod: "revenue this period",
    recentOrders: "Recent Orders",
    orderId: "Order ID",
    product: "Product",
    totalTND: "Total (TND)",
    noOrdersMatch: "No orders match your filter",
    phone: "Phone",

    // --- Employee Dashboard ---
    employeeDashboard: "Employee Dashboard",
    limitedAccess: "Limited access view.",

    // --- Campaigns ---
    campaignManagement: "Campaign Management",
    campaignSubtitle: "Fév 2026 · EMM ERP · v2.4",
    newCampaign: "+ New Campaign",
    totalCampaigns: "Total Campaigns",
    activeNow: "Active Now",
    running: "running",
    totalLeads: "Total Leads",
    generated: "generated",
    totalBudget: "Total Budget",
    allocated: "allocated",
    allCampaigns: "All Campaigns",
    searchCampaign: "Search campaign...",
    noCampaignsMatch: "No campaigns match your filter",
    campaign: "Campaign",
    channel: "Channel",
    leads: "Leads",
    budgetCol: "Budget",
    spent: "Spent",

    // --- Promotions ---
    promotionsManagement: "Promotions Management",
    promotionsSubtitle: "Fév 2026 · EMM ERP · v2.4",
    newPromotion: "+ New Promotion",
    totalPromos: "Total Promos",
    scheduledKpi: "Scheduled",
    upcoming: "upcoming",
    avgDiscount: "Avg Discount",
    acrossAllPromos: "across all promos",
    allPromotions: "All Promotions",
    searchPromotion: "Search promotion...",
    noPromotionsMatch: "No promotions match your filter",
    promotion: "Promotion",
    discount: "Discount",
    code: "Code",
    start: "Start",
    end: "End",
    runningNow: "running now",

    // --- Analytics Page ---
    emailOpenRate: "Email Open Rate",
    clickThroughRate: "Click-Through Rate",
    impressions: "Impressions",
    bounceRate: "Bounce Rate",
    avgSession: "Avg Session",
    timeOnSite: "time on site",
    totalReach: "Total Reach",
    uniqueVisitors: "unique visitors",
    unsubscribes: "Unsubscribes",
    emailList: "of email list",
    performanceTrends: "Performance Trends",
    monthlyEmailCtr: "Monthly email open rate & CTR",
    avgOpenRate: "Avg Open Rate",
    avgCtr: "Avg CTR",
    emailOpenRateChart: "Email Open Rate",
    clickThroughRateChart: "Click-Through Rate",
    channelPerformance: "Channel Performance",
    openCtrConv: "Open rate · CTR · Conversion",

    // --- Marketing Dashboard ---
    budgetUsed: "Budget Used",
    campaignRoi: "Campaign ROI",
    costPerLead: "Cost Per Lead",
    currentlyRunning: "currently running",
    newLeads: "New Leads",
    avgCpm: "Avg CPM",
    costPerThousand: "cost per 1,000 impressions",
    campaignOverview: "Campaign Overview",
    avgConversion: "Avg Conversion",
    leadsPerMonth: "Leads Per Month",
    conversionRate: "Conversion Rate",
    conversionRateChart: "Conversion Rate",
    topCampaigns: "Top Campaigns",
    leadsGeneratedThisMonth: "Leads generated this month",
    growthGoals: "Growth Goals",
    conversionRateTarget: "Conversion Rate Target",
    leadAcquisition: "Lead Acquisition",
    budgetEfficiency: "Budget Efficiency",

    // --- Segmentation ---
    customerSegmentation: "Customer Segmentation",
    segmentationSubtitle: "Fév 2026 · EMM ERP · v2.4",
    newSegment: "+ New Segment",
    totalCustomers: "Total Customers",
    acrossAllSegments: "across all segments",
    segments: "Segments",
    defined: "defined",
    growingKpi: "Growing",
    positiveTrend: "positive trend",
    atRiskKpi: "At Risk",
    needsAttention: "needs attention",
    customerSegmentsTable: "Customer Segments",
    searchSegment: "Search segment...",
    noSegmentsMatch: "No segments match your filter",
    segment: "Segment",
    customers: "Customers",
    avgSpend: "Avg Spend",
    growth: "Growth",
    segmentSizes: "Segment Sizes",
    customersPerSegment: "Customers per segment",
    fastestGrowing: "Fastest Growing",
  },

  fr: {
    // --- Shared / Nav ---
    live: "EN DIRECT",
    profile: "Profil",
    settings: "Paramètres",
    logout: "Déconnexion",
    erpSubtitle: "EMM Hardware ERP · V2.4",

    // --- Sidebar ---
    dashboard: "Tableau de bord",
    hr: "RH",
    marketing: "Marketing",
    onlineSales: "Ventes en ligne",
    employees: "Employés",
    attendance: "Présence",
    payroll: "Paie",
    performance: "Performance",
    reports: "Rapports",
    productCatalog: "Catalogue produits",
    onlineOrders: "Commandes en ligne",
    stockProduction: "Stock & Production",
    deliveryTracking: "Suivi des livraisons",
    returnsRefunds: "Retours & Remboursements",
    campaigns: "Campagnes",
    analytics: "Analytique",
    segmentation: "Segmentation",
    budget: "Budget",
    promotions: "Promotions",


    // --- Sales Dashboard ---
    onlineSalesDashboard: "Tableau de bord Ventes en ligne",
    totalRevenue2: "Chiffre d'affaires total",
    pendingShipments: "Expéditions en attente",
    returns: "Retours",
    avgOrderValue: "Valeur moy. commande",
    perTransaction: "par transaction",
    newCustomers: "Nouveaux clients",
    customerLtv: "LTV client",
    avgLifetime: "durée de vie moyenne",
    revenueOverview: "Aperçu des revenus",
    monthlyPerf: "Performance mensuelle",
    revenueUSD: "Revenus (USD)",
    topProducts: "Meilleurs produits",
    unitsSoldMonth: "Unités vendues ce mois",
    searchOrdersPlaceholder: "Rechercher des commandes...",
    noOrdersMatchFilter: "Aucune commande ne correspond",
    salesByChannel: "Ventes par canal",
    revenueSplitMonth: "Répartition des revenus ce mois",
    directSales: "Ventes directes",
    wholesale: "Gros",
    distributor: "Distributeur",
    onlineStore: "Boutique en ligne",
    monthlyGoal: "Objectif mensuel",
    daysLeft: "8 jours restants",
    invoice: "Facture",
    report: "Rapport",
    shipment: "Expédition",
    todayChange: "-3 aujourd'hui",

    // --- Catalog Page ---
    productCatalogTitle: "Catalogue Produits",
    addProduct: "Ajouter un produit",
    totalProducts: "Total Produits",
    inStock: "En Stock",
    lowStock: "Stock Faible",
    catalogValue: "Valeur du Catalogue",
    categories: "Catégories",
    outOfStock: "Rupture de Stock",
    avgPrice: "Prix Moy.",
    totalSkus: "Total SKUs",
    searchProducts: "Rechercher des produits...",
    noProductsMatch: "Aucun produit ne correspond",
    productTypes: "types de produits",
    needsRestocking: "réapprovisionnement nécessaire",
    perUnit: "par unité",
    activeListings: "références actives",
    inStockLabel: "En Stock",
    lowStockLabel: "Stock Faible",
    outOfStockLabel: "Rupture",
    needsReorder: "réapprovisionner",
    thisMonth2: "+3 ce mois",
    tndEquivalent: "équivalent TND",

    // --- Orders Page ---
    onlineOrders: "Commandes en Ligne",
    newOrder2: "Nouvelle Commande",
    totalOrdersKpi2: "Total Commandes",
    completedKpi2: "Terminées",
    processingKpi: "En cours",
    pendingKpi2: "En attente",
    allOrdersTitle: "Toutes les Commandes",
    searchOrders2: "Rechercher des commandes...",
    noOrdersMatch2: "Aucune commande ne correspond",
    avgOrder: "Commande Moy.",
    completionRate: "Taux de Complétion",
    fulfilled: "exécutées",
    inTransitSub: "en transit",
    awaitingSub: "en attente",
    allOrders: "Toutes les commandes",
    order: "Commande",
    orders: "commandes",
    perOrder: "par commande",
    thisPeriod: "cette période",
    fulfillment: "exécution",
    price: "Prix",
    stock: "Stock",
    category: "Catégorie",
    amount: "Montant",
    customer: "Client",

    // --- Returns Page ---
    returnsRefunds: "Retours & Remboursements",
    newReturn: "Nouveau Retour",
    totalReturns: "Total Retours",
    pendingReview: "En Attente d'Examen",
    refunded: "Remboursé",
    totalValue: "Valeur Totale",
    refundRate: "Taux de Remboursement",
    refundedValue: "Montant Remboursé",
    avgReturn: "Retour Moy.",
    rejectedKpi2: "Rejeté",
    returnRequests: "Demandes de Retour",
    searchReturns: "Rechercher des retours...",
    noReturnsMatch: "Aucun retour ne correspond",
    reason: "Motif",
    ofTotalOrders: "des commandes totales",
    paidOut: "payé",
    perReturn: "par retour",
    notApproved: "non approuvé",
    actionNeeded: "action requise",
    processed: "traités",
    inReturns: "en retours",
    requests: "demandes",

    // --- Stock Page ---
    stockProduction2: "Stock & Production",
    restockOrder: "Commande de Réappro.",
    totalSkusKpi: "Total SKUs",
    inStockKpi: "En Stock",
    alertsKpi: "Alertes",
    outOfStockKpi: "Rupture de Stock",
    totalUnits: "Total Unités",
    reorderNeeded: "Réapprovisionnement",
    lastSync: "Dernière Sync.",
    stockLevels: "Niveaux de Stock",
    searchStock: "Rechercher stock...",
    noStockMatch: "Aucun article ne correspond",
    stockVsMinimum: "Stock vs Minimum",
    stockAlerts: "Alertes Stock",
    itemsNeedingAttention: "Articles nécessitant attention",
    currentLevelsVsThreshold: "Niveaux actuels vs seuil de réapprovisionnement",
    acrossAllSkus: "sur tous les SKUs",
    skusBelowMinimum: "SKUs sous le minimum",
    realTimeData: "données en temps réel",
    tracked: "suivis",
    healthy: "sains",
    needsAction: "action requise",
    reorderNow: "réapprovisionner maintenant",
    minimum: "Minimum",
    reorderQty: "Qté Réappro.",
    current: "Actuel",

    // --- Tracking Page ---
    deliveryTracking2: "Suivi des Livraisons",
    newShipment: "Nouvelle Expédition",
    totalShipments: "Total Expéditions",
    delivered: "Livré",
    inTransit: "En Transit",
    failedKpi: "Échoué",
    pendingShip: "En Attente",
    deliveryRate: "Taux de Livraison",
    carriersKpi: "Transporteurs",
    avgEta: "DL Moy.",
    shipmentTracker: "Suivi des Expéditions",
    searchShipments: "Rechercher des expéditions...",
    noShipmentsMatch: "Aucune expédition ne correspond",
    shipmentsByCarrier: "Expéditions par Transporteur",
    volumeSplitMonth: "Répartition du volume ce mois",
    activityFeed: "Fil d'Activité",
    liveUpdates: "Mises à jour en direct",
    quickActions: "Actions Rapides",
    shortcuts: "Raccourcis",
    deliveryGoal: "Objectif de Livraison",
    trackingNo: "N° Suivi",
    carrier: "Transporteur",
    shipped: "Expédié",
    eta: "DL Prévue",
    thisMonthSub: "ce mois",
    completedSub: "terminées",
    onTheWay: "en chemin",
    needsActionSub: "action requise",
    awaitingDispatch: "en attente d'expédition",
    successRate: "taux de succès",
    daysToDeliver: "jours pour livrer",
    stillMoving: "encore en transit",
    shipments: "expéditions",

    // --- Login ---
    authLabel: "Authentification",
    signInTitle: "Connectez-vous à votre compte",
    emailLabel: "E-mail",
    emailPlaceholder: "vous@entreprise.com",
    passwordLabel: "Mot de passe",
    signInButton: "Se connecter →",
    invalidCredentials: "E-mail ou mot de passe invalide",
    copyright: "© 2026 EMM Hardware ERP",
    erpTagline: "Plateforme de gestion d'entreprise sécurisée pour les RH, le Marketing, les Ventes et les Opérations.",
    statRevenue: "Chiffre d'affaires",
    statOrders: "Commandes actives",
    statUptime: "Disponibilité",

    // --- Profile ---
    accountLabel: "Compte",
    myProfile: "Mon Profil",
    profileInformation: "Informations du profil",
    fullName: "Nom complet",
    emailField: "E-mail",
    roleField: "Rôle",
    saveChanges: "Enregistrer",

    // --- Settings ---
    systemLabel: "Système",
    settingsTitle: "Paramètres",
    securitySection: "Sécurité",
    changePassword: "Changer le mot de passe",
    enableTwoFactor: "Activer l'authentification à deux facteurs",
    preferencesSection: "Préférences",
    enableNotifications: "Activer les notifications",
    toggleDarkMode: "Mode sombre",
    dangerZone: "Zone de danger",
    deleteAccount: "Supprimer le compte",

    // --- Common table/page actions ---
    export: "Exporter",
    exportCsv: "Exporter CSV",
    exportPdf: "Exporter PDF",
    exportExcel: "Exporter Excel",
    exportAll: "Tout exporter",
    search: "Rechercher",
    searchEmployee: "Rechercher un employé...",
    searchUser: "Rechercher un utilisateur...",
    searchOrders: "Rechercher des commandes...",
    allStatus: "Tous les statuts",
    allTypes: "Tous les types",
    allRatings: "Toutes les notes",
    noResults: "Aucun résultat ne correspond",
    ofText: "sur",
    records: "enregistrements",

    // --- Status labels ---
    active: "Actif",
    inactive: "Inactif",
    onLeave: "En congé",
    approved: "Approuvé",
    pending: "En attente",
    rejected: "Rejeté",
    completed: "Terminé",
    processing: "En cours",
    cancelled: "Annulé",
    paid: "Payé",
    hold: "Bloqué",
    excellent: "Excellent",
    good: "Bien",
    average: "Moyen",
    poor: "Insuffisant",
    paused: "En pause",
    planned: "Planifié",
    scheduled: "Programmé",
    growing: "En croissance",
    stable: "Stable",
    declining: "En baisse",
    atRisk: "À risque",

    // --- Admin Dashboard ---
    adminDashboard: "Tableau de bord Admin",
    adminSubtitle: "Fév 2026 · EMM ERP · v2.4",
    newReport: "+ Nouveau rapport",
    totalEmployees: "Total employés",
    monthlyRevenue: "Revenu mensuel (TND)",
    totalOrders: "Total commandes",
    activeCampaigns: "Campagnes actives",
    allDepartments: "tous départements",
    currentlyWorking: "en poste actuellement",
    allTime: "cumulé",
    activeCampaignsCount: "actives ce mois",
    newUsers: "Nouveaux utilisateurs",
    serverLoad: "Charge serveur",
    pendingApprovals: "Approbations en attente",
    securityScore: "Score de sécurité",
    optimalPerformance: "performance optimale",
    requiresAction: "action requise",
    lastAuditPassed: "dernier audit réussi",
    businessOverview: "Vue d'ensemble",
    monthlyPerformance: "Performance mensuelle",
    revenueTND: "Revenus (TND)",
    ordersPerMonth: "Commandes / Mois",
    recentUsers: "Utilisateurs récents",
    topModules: "Top Modules",
    usageThisMonth: "Utilisation ce mois",
    systemHealth: "Santé du système",
    databaseUsage: "Usage base de données",
    apiStability: "Stabilité API",
    totalRevenue: "Chiffre d'affaires",

    // --- HR Dashboard ---
    hrDashboard: "Tableau de bord RH",
    pendingPayroll: "Paie en attente (TND)",
    workingHours: "Heures travaillées",
    attrition: "Attrition",
    totalEmployeesKpi: "Total employés",
    activeWorkforce: "effectif actif",
    performanceScore: "Score de performance",
    newHires: "Nouvelles recrues",
    avgTenure: "Ancienneté moy.",
    avgPerEmployee: "moyenne par employé",
    payrollOverview: "Aperçu de la paie",
    totalPayroll: "Total paie",
    avgPerformance: "Perf. moyenne",
    payrollTND: "Paie (TND)",
    performanceScoreChart: "Score de performance",
    topPerformers: "Meilleurs collaborateurs",
    performanceScoreThisMonth: "Score de performance ce mois",
    addEmployee: "+ Ajouter un employé",

    // --- HR Employees ---
    employeeManagement: "Gestion des employés",
    humanResources: "Ressources Humaines · EMM ERP · v2.4",
    totalEmployeesKpiShort: "Total employés",
    onLeaveKpi: "En congé",
    cdiContracts: "Contrats CDI",
    permanentStaff: "personnel permanent",
    allEmployees: "Tous les employés",
    employee: "Employé",
    position: "Poste",
    dept: "Dépt",
    contract: "Contrat",
    status: "Statut",
    joined: "Arrivée",
    noEmployeesMatch: "Aucun employé ne correspond",

    // --- HR Attendance ---
    attendanceAbsences: "Présences & Absences",
    totalRequests: "Total demandes",
    thisMonth: "ce mois-ci",
    approvedKpi: "Approuvées",
    processed: "traitées",
    pendingKpi: "En attente",
    awaitingAction: "action requise",
    rejectedKpi: "Rejetées",
    notApproved: "non approuvées",
    attendanceRecords: "Registre de présence",
    approveRequests: "Approuver les demandes",
    date: "Date",
    type: "Type",
    hours: "Heures",
    noAttendanceMatch: "Aucun enregistrement ne correspond",
    annualLeave: "Congé annuel",
    sickLeave: "Congé maladie",
    remoteWork: "Télétravail",
    unpaidLeave: "Congé sans solde",
    unauthorized: "Non autorisé",

    // --- HR Payroll ---
    payrollManagement: "Gestion de la paie",
    totalNetPayroll: "Paie nette totale",
    totalBonuses: "Total primes",
    distributed: "distribuées",
    slipsPaid: "Bulletins payés",
    pendingHold: "En attente / Bloqué",
    payrollRecords: "Registre de paie",
    generatePayslips: "Générer les bulletins",
    baseTND: "Base (TND)",
    bonus: "Prime",
    deductions: "Déductions",
    netTND: "Net (TND)",
    month: "Mois",
    noPayrollMatch: "Aucun enregistrement ne correspond",

    // --- HR Performance ---
    performanceTracking: "Suivi des performances",
    avgScore: "Score moy.",
    teamAverage: "moyenne équipe",
    excellentCount: "Excellent",
    topPerformersKpi: "top collaborateurs",
    evaluations: "Évaluations",
    thisCycle: "ce cycle",
    needsReview: "À revoir",
    belowTarget: "en dessous de l'objectif",
    evaluationsTable: "Évaluations",
    score: "Score",
    manager: "Responsable",
    rating: "Note",
    addEvaluation: "+ Ajouter une évaluation",
    topPerformersThisCycle: "Score de performance ce cycle",
    noPerformanceMatch: "Aucun enregistrement ne correspond",

    // --- HR Reports ---
    hrReports: "Rapports RH",
    totalReports: "Total rapports",
    available: "disponibles",
    generatedToday: "Générés aujourd'hui",
    thisSession: "cette session",
    monthlyExports: "Exports mensuels",
    pendingReports: "Rapports en attente",
    notYetGenerated: "pas encore générés",
    recentExports: "Exports récents",
    latestFiles: "Derniers fichiers téléchargés",
    redownload: "Re-télécharger",
    payrollReport: "Rapport de paie",
    payrollReportDesc: "Décomposition mensuelle des salaires avec primes et déductions",
    absenceReport: "Rapport d'absences",
    absenceReportDesc: "Congés, arrêts maladie et absences des employés",
    employeeList: "Liste des employés",
    employeeListDesc: "Répertoire complet du personnel avec contrats et statuts",
    performanceReport: "Rapport de performance",
    performanceReportDesc: "Scores, notes et évaluations de l'équipe",
    monthly: "Mensuel",
    onDemand: "À la demande",
    quarterly: "Trimestriel",
    lastGenerated: "Dernier généré",

    // --- Sales / Admin pages ---
    hrEmployees: "Employés RH",
    marketingEmployees: "Employés Marketing",
    marketingDept: "Département Marketing · EMM ERP · v2.4",
    hrDept: "Ressources Humaines · EMM ERP · v2.4",
    totalHRStaff: "Total équipe RH",
    totalMarketing: "Total Marketing",
    inDepartment: "dans le département",
    salesOrders: "Commandes",
    onlineSalesSubtitle: "Ventes en ligne · EMM ERP · v2.4",
    newOrder: "+ Nouvelle commande",
    totalOrdersKpi: "Total commandes",
    completedKpi: "Terminées",
    successfullyDone: "traitées avec succès",
    pendingCount: "En attente",
    revenueThisPeriod: "revenus sur la période",
    recentOrders: "Commandes récentes",
    orderId: "N° commande",
    customer: "Client",
    product: "Produit",
    totalTND: "Total (TND)",
    noOrdersMatch: "Aucune commande ne correspond",
    phone: "Téléphone",

    // --- Employee Dashboard ---
    employeeDashboard: "Tableau de bord Employé",
    limitedAccess: "Accès limité.",

    // --- Campaigns ---
    campaignManagement: "Gestion des campagnes",
    campaignSubtitle: "Fév 2026 · EMM ERP · v2.4",
    newCampaign: "+ Nouvelle campagne",
    totalCampaigns: "Total campagnes",
    activeNow: "Actives maintenant",
    running: "en cours",
    totalLeads: "Total prospects",
    generated: "générés",
    totalBudget: "Budget total",
    allocated: "alloué",
    allCampaigns: "Toutes les campagnes",
    searchCampaign: "Rechercher une campagne...",
    noCampaignsMatch: "Aucune campagne ne correspond",
    campaign: "Campagne",
    channel: "Canal",
    leads: "Prospects",
    budgetCol: "Budget",
    spent: "Dépensé",

    // --- Promotions ---
    promotionsManagement: "Gestion des promotions",
    promotionsSubtitle: "Fév 2026 · EMM ERP · v2.4",
    newPromotion: "+ Nouvelle promotion",
    totalPromos: "Total promos",
    scheduledKpi: "Programmées",
    upcoming: "à venir",
    avgDiscount: "Remise moy.",
    acrossAllPromos: "sur toutes les promos",
    allPromotions: "Toutes les promotions",
    searchPromotion: "Rechercher une promotion...",
    noPromotionsMatch: "Aucune promotion ne correspond",
    promotion: "Promotion",
    discount: "Remise",
    code: "Code",
    start: "Début",
    end: "Fin",
    runningNow: "en cours",

    // --- Analytics Page ---
    emailOpenRate: "Taux d'ouverture email",
    clickThroughRate: "Taux de clics",
    impressions: "Impressions",
    bounceRate: "Taux de rebond",
    avgSession: "Session moy.",
    timeOnSite: "temps sur site",
    totalReach: "Portée totale",
    uniqueVisitors: "visiteurs uniques",
    unsubscribes: "Désabonnements",
    emailList: "de la liste email",
    performanceTrends: "Tendances de performance",
    monthlyEmailCtr: "Taux d'ouverture & CTR mensuels",
    avgOpenRate: "Taux d'ouverture moy.",
    avgCtr: "CTR moy.",
    emailOpenRateChart: "Taux d'ouverture email",
    clickThroughRateChart: "Taux de clics",
    channelPerformance: "Performance par canal",
    openCtrConv: "Ouverture · CTR · Conversion",

    // --- Marketing Dashboard ---
    budgetUsed: "Budget utilisé",
    campaignRoi: "ROI campagne",
    costPerLead: "Coût par lead",
    currentlyRunning: "en cours d'exécution",
    newLeads: "Nouveaux leads",
    avgCpm: "CPM moy.",
    costPerThousand: "coût pour 1 000 impressions",
    campaignOverview: "Aperçu des campagnes",
    avgConversion: "Conversion moy.",
    leadsPerMonth: "Leads par mois",
    conversionRate: "Taux de conversion",
    conversionRateChart: "Taux de conversion",
    topCampaigns: "Meilleures campagnes",
    leadsGeneratedThisMonth: "Leads générés ce mois",
    growthGoals: "Objectifs de croissance",
    conversionRateTarget: "Objectif de conversion",
    leadAcquisition: "Acquisition de leads",
    budgetEfficiency: "Efficacité budgétaire",

    // --- Segmentation ---
    customerSegmentation: "Segmentation clients",
    segmentationSubtitle: "Fév 2026 · EMM ERP · v2.4",
    newSegment: "+ Nouveau segment",
    totalCustomers: "Total clients",
    acrossAllSegments: "tous segments confondus",
    segments: "Segments",
    defined: "définis",
    growingKpi: "En croissance",
    positiveTrend: "tendance positive",
    atRiskKpi: "À risque",
    needsAttention: "nécessite attention",
    customerSegmentsTable: "Segments clients",
    searchSegment: "Rechercher un segment...",
    noSegmentsMatch: "Aucun segment ne correspond",
    segment: "Segment",
    customers: "Clients",
    avgSpend: "Panier moy.",
    growth: "Croissance",
    segmentSizes: "Taille des segments",
    customersPerSegment: "Clients par segment",
    fastestGrowing: "Croissance la plus rapide",
  },
} as const;

export type Language = "en" | "fr";
export type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const saved = localStorage.getItem("language") as Language | null;
    if (saved === "en" || saved === "fr") setLanguageState(saved);
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: TranslationKey): string => translations[language][key];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider");
  return ctx;
}